### ISSUE TITLE
使用方法

### ISSUE THREAD

**Issue by LiuXuefeng163** [ImSwordTooth/findwhatever#1]
你好，不方便上googleplay去下载，不懂js的情况下，怎么使用这个插件？

**Comment by ImSwordTooth** [comment]
sorry，刚看到，可以在这里 https://crxdl.com 下载离线的扩展程序安装包。本插件的 id 是 pdpkckoiaiinjlhddhcoknjhdncepnbo

下载完之后在扩展程序界面，打开开发者模式，然后把 .crx 文件拖拽到界面里就安装成功了。

**Comment by LiuXuefeng163** [comment]
非常感谢，可以使用了。
