### ISSUE TITLE
希望默认调出窗口之后，光标定位在输入框

### ISSUE THREAD

**Issue by eryajf** [ImSwordTooth/findwhatever#2]
我定义了快捷键，但是按下快捷键之后，光标没有再输入框内，不知是否方便自动定位在输入框里。

**Comment by ImSwordTooth** [comment]
已修复，提交发布了，明天应该就能用了。
现在打开时会手动给 input focus()。
另外顺便修复了选中的文本不能自动填写到文本框的bug。

---
_刚看到谷歌邮箱里的消息，我这就换成 QQ邮箱。。。_
_感谢支持，方便的话去商店评价下~_

**Comment by eryajf** [comment]
辛苦🤝

**Comment by ImSwordTooth** [comment]
问题应该解决了，先关闭了
